### ISSUE TITLE
Where can I see documentation?

### ISSUE THREAD

**Issue by loganbaby** [g-battaglia/kerykeion#100]
Documentation is not found with 404 code for now. Where I can see full library doc?

**Comment by kubow** [comment]
clone the repo and browse content locally (is the way I workaround the missing deployment)

**Comment by g-battaglia** [comment]
Hi, sorry I'm currently out of time for fixing the docs site, I'll fix it as soon as I can, for now you can do like @kubow suggested. Sorry for the inconvenience!

**Comment by g-battaglia** [comment]
Hi, I've just fixed the docs, the URL is the same as before:
https://g-battaglia.github.io/kerykeion/kerykeion.html
