### ISSUE TITLE
Whole Sign System

### ISSUE THREAD

**Issue by 1OnesAndZeros0** [g-battaglia/kerykeion#105]
I don't see any documentation about changing house systems, but I was able to modify the astrological_subject.py to use "swisseph" with the "whole sign" option by adding b'W' as seen in the following line:

`self.houses_degree_ut = swe.houses(self.julian_day, self.lat, self.lng, b'W')[0]`

But now the ASC and MC are showing as 000000.

It's so very close to working, but can you provide any insight into how to get the appropriate ASC, MC, etc calculations? They were accurate before I made the change.

Thanks and amazing work by the way!

**Comment by molnaredom** [comment]
what type of housing system the application is currently using by default?

**Comment by 1OnesAndZeros0** [comment]
> what type of housing system the application is currently using by default?

Thanks for replying! I'm still trying to get this working for my girlfriend. It will make her very happy!

It is using the Placidus house system.

**Comment by g-battaglia** [comment]
Closing, here the example of the implementation:
https://www.kerykeion.net/docs/examples/houses-systems

**Comment by 1OnesAndZeros0** [comment]
Thank you so much for implementing the house system selection! This is great!

However there's still the problem of showing the Asc and Mc as 00°00'00. Using the John Lenon example, they should be Asc: 16°04' and Mc: 5°33' (rounded by the generator I used) for the Whole System.

Unless there's something I'm doing wrong?
