### ISSUE TITLE
How to get SVG code of chart?

### ISSUE THREAD

**Issue by loganbaby** [g-battaglia/kerykeion#106]
I have this code snippet:

```python
@app.get("/get_svg_code")
def make_svg(name: str, year: int, month: int, day: int, hour: int, minute: int, city: str):
    kanye = AstrologicalSubject(name, year, month, day, hour, minute, city)

    pic = KerykeionChartSVG(kanye, chart_type="Natal")

    return pic.makeTemplate()
```

but this return wrong code. How can I do it correctly?

**Comment by loganbaby** [comment]
I can get code by ```return pic.template``` but I can't insert this data into my web page into ```<svg>``` tag. how can I do it?

**Comment by g-battaglia** [comment]
Hi, it look's it's not a problem specific to kerykeion but to the web framework that you are using. The answer depends of the technology, in general terms you can't return a raw SVG from a request, it must be correctly formatted. The format depends of what you need to be inside the response.
