### ISSUE TITLE
Set_output_directory make issue.

### ISSUE THREAD

**Issue by LeoBline** [g-battaglia/kerykeion#107]
![image](https://github.com/g-battaglia/kerykeion/assets/50190407/4894125c-14fe-4dae-80e3-4852b390b3d1)
when i try to set the output directory this error happen.

**Comment by gognjen** [comment]
I think you should do something like this:

from pathlib import Path
name.set_output_directory(Path("C:\\Users\\25815\\Desktop\\DI")
