### ISSUE TITLE
How to change language using object KerykeionChartSVG?

### ISSUE THREAD

**Issue by loganbaby** [g-battaglia/kerykeion#111]
I need to change language for KerykeionChartSVG object.

Example:
```py
pic.language_settings = get_settings().language_settings[lang]
print(pic.language_settings)
```
but it didn't work. help

**Comment by loganbaby** [comment]
full code:

```py
@app.get("/make_full_svg")
def make_full_svg(name: str, year: int, month: int, day: int, hour: int, minute: int, city: str, lang: str):
    kanye = AstrologicalSubject(name, year, month, day, hour, minute, city)

    pic = KerykeionChartSVG(kanye, chart_type="Natal")
    pic.language_settings = get_settings().language_settings[lang]
    print(pic.language_settings)

    pic.set_output_directory(Path('./charts'))
    pic.makeSVG()
    print(pic.language_settings)

    return FileResponse(f'{str(pic.chartname)}')
```

**Comment by D1fify** [comment]
Haven't found a solution yet?

**Comment by loganbaby** [comment]
Have one. I found a config file in sources and set up this for my goals (added some languages). Then, I use an non required argument in function that can change language of file (see docs, I found there). So, I can generate in different langs

Example in my site: astrohelp24.com

**Comment by D1fify** [comment]
How can I connect with you? Maybe on telegram

**Comment by g-battaglia** [comment]
@D1fify I created a doc page with examples on how to change language:
[here](https://www.kerykeion.net/docs/examples/change-language)

**Comment by loganbaby** [comment]
@D1fify yeah you can connect with me in Telegram. My social links in my profile
