### ISSUE TITLE
The number of houses is wrong when generating the SVG file

### ISSUE THREAD

**Issue by Intekai** [g-battaglia/kerykeion#117]
The number of houses is wrong when generating the SVG file, e.g. it puts bull in house 8 ms the correct one is house 9.

**Comment by g-battaglia** [comment]
Can you share a code snippet of the problem?

**Comment by Intekai** [comment]
@app.route("/svgchartsingle", methods=['POST'])
def svgchartsingle():
    data = request.get_json()
    
    if data is None:
        return jsonify({'error': 'Invalid JSON data'}), 400
    
    chart_type = data['chart_type']
    
    first_name = data['first']['name']
    first_year = data['first']['year']
    first_month = data['first']['month']
    first_day = data['first']['day']
    first_hour = data['first']['hour']
    first_minute = data['first']['minute']
    first_city = data['first']['city']
    first_nation = data['first']['nation']
    first_lng = data['first']['lng']
    first_lat = data['first']['lat']
    first_tz_str = data['first']['tz_str']
    first_zodiac_type=data['first']['zodiac_type']
    
    
    first = AstrologicalSubject(
        name=first_name,
        year=first_year,
        month=first_month,
        day=first_day,
        hour=first_hour,
        minute=first_minute,
        city=first_city,
        nation=first_nation,
        lng=first_lng,
        lat=first_lat,
        tz_str=first_tz_str,
        zodiac_type=first_zodiac_type,
        geonames_username="alimohsin" 
)

    
    name = KerykeionChartSVG(first_obj=first,
                             chart_type=chart_type,
                             new_output_directory=".",
                             )
    
    
    
    return name.makeTemplate()

**Comment by Intekai** [comment]
I also looked at the reports the houses are wrong

**Comment by Intekai** [comment]
![image](https://github.com/g-battaglia/kerykeion/assets/68114285/90d3fa73-bcca-4dd4-bc47-16c8a7199581)

**Comment by Intekai** [comment]
![image](https://github.com/g-battaglia/kerykeion/assets/68114285/f50da8b7-7bf1-4faa-86c3-cc30be929238)

**Comment by sengiv** [comment]
> The number of houses is wrong when generating the SVG file, e.g. it puts bull in house 8 ms the correct one is house 9.

@Intekai I suspect 🤔 you're seeing discrepancy because of different "**Ayanamsa**". 
VedAstro defaults to "**Lahiri**", you'll have to change to "**Fagan Bradley**" or something else to match with the default **Ayanamsa** used by Kerykeion (which i'm not sure which is 😁)

**Comment by g-battaglia** [comment]
@Intekai I confirm what said  by @sengiv, so far Kerykeion has just Fagan Bradley as sidereal mode. In the next release major release (version 5.0.0) I will definitely implement all the possibile sidereal modes.

**Comment by Intekai** [comment]
hello the calculation is now correct but not the order of the houses which is reversed you see it anti-clockwise
![image](https://github.com/g-battaglia/kerykeion/assets/68114285/5ff187d8-c812-4f56-b4a0-1e7842b5450a)

**Comment by g-battaglia** [comment]
Sorry I didn't understand, the houses or the sings are in the wrong position?
You mean that the whole chart should be reversed?

**Comment by g-battaglia** [comment]
Closing since no other answers, I consider it fixed.
