### ISSUE TITLE
juno

### ISSUE THREAD

**Issue by joulethieff** [g-battaglia/kerykeion#119]
Thank you for creating the program.

How do I add an asteroid like juno?

**Comment by g-battaglia** [comment]
Hi, thanks! So far it's not possible to have juno available, also implementing is a little bit of a mess, you can check in the old commits where I implemented Chiron. There are many changes that should be done. I'll put it in the todo list for the version 5 though! It will implement many new "planets". 
BTW if like the project consider donating!
