### ISSUE TITLE
Some cities are not found

### ISSUE THREAD

**Issue by to175** [g-battaglia/kerykeion#123]
Hello, I would like to ask if my incident is linked to this lib or not and if anyone had the same issue...

I suppose it is related to the geolocation API.

We have some big and small cities that are found and other that are not found. Do you now why ? I don't understant that famous cities "Orléans" (500k) or "La rochelle" (100k) are not found. "No data found for this city"

**Comment by g-battaglia** [comment]
Hi, can you share a code snippet of the issue?
