### ISSUE TITLE
Operating system specific format string

### ISSUE THREAD

**Issue by JustinHildenbrand** [g-battaglia/kerykeion#131]
In Windows, '-' is not supported to eliminate leading zeros in datetime.strftime.  Instead, '#' should be used.  Trying to use '-' for this purpose in Windows raises a ValueError with description "Invalid format string".  For cross-platform compatibility, consider checking the OS then selecting the appropriate formatting string.

https://github.com/g-battaglia/kerykeion/blob/ce3cbc82df0bd8bc8862b60d21d63704fa8737d5/kerykeion/charts/kerykeion_chart_svg.py#L575

**Comment by g-battaglia** [comment]
Hi, @JustinHildenbrand, thanks for reporting the issue!
Should be fixed in V4.16.5, can you confirm?
