### ISSUE TITLE
Having issue with MakeSvgInstance 

### ISSUE THREAD

**Issue by aduvaita** [g-battaglia/kerykeion#34]
Code :
import kerykeion as kr
from kerykeion.utilities.charts import MakeSvgInstance
first = kr.KrInstance("Jack", 1990, 6, 15, 15, 15, "Roma")
second = kr.KrInstance("Jane", 1991, 10, 25, 21, 00, "Roma")
name = MakeSvgInstance(first, chart_type="Composite", second_obj=second)
name.makeSVG()
print(len(name.aspects_list))

Error:
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1341: character maps to <undefined>

I do run an example, shows this error. Please help to fix this issue as earliest.

**Note:** I have updated your recent version as well
" Successfully installed cattrs-1.10.0 kerykeion-2.3.2 requests-cache-0.9.3 url-normalize-1.4.3 "

Thanks

**Comment by g-battaglia** [comment]
Hi, now should be fixed, pleas report if the problem i still there!

**Comment by aduvaita** [comment]
Hi,

Thanks for the update. But still facing the same issue

**Comment by g-battaglia** [comment]
What kerykeion version are you running?

**Comment by g-battaglia** [comment]
Also what OS and what os version are you using?
