### ISSUE TITLE
Error with Aspect() & Planet_house() and not working

### ISSUE THREAD

**Issue by aduvaita** [g-battaglia/kerykeion#35]
Code :
print(kanye.planets_house()[0]) 
print(kanye.aspects()['all']['Sun']) 

Error :
AttributeError: 'KrInstance' object has no attribute 'planets_house'
AttributeError: 'KrInstance' object has no attribute 'aspects'

I am executing the same example but throws error. Update the packages, still facing issue.

Thanks

**Comment by g-battaglia** [comment]
Hi, those functionalities have been removed from version 3.0!
