### ISSUE TITLE
How can I show more data in the svg file?

### ISSUE THREAD

**Issue by DeadNooBChick** [g-battaglia/kerykeion#36]
hi,
How can I show the True_node in the svg file? also could i show more aspect like 45 degrees, 135 degrees, 150 degrees, etc?
thx a lot

**Comment by g-battaglia** [comment]
Hi, you should edit or set a new:
[kr.config.json](https://github.com/g-battaglia/kerykeion/blob/develop/kerykeion/kr.config.json)
I'll write it down in the readme soon
