### ISSUE TITLE
lat lon as inputs still use 'London' as location default

### ISSUE THREAD

**Issue by paladinic** [g-battaglia/kerykeion#41]
When the lat, lng inputs are passed to the KrInstance function it ignores those inputs and uses 'London' as the country.

**Comment by g-battaglia** [comment]
Hi, to prevent the fallback location (London) you should always pass also the timezone string, eg:
```python
KrInstance("Test", 1993, 10, 10, 12, 12, lng=2.1, lat=2.1, tz_str='Europe/Rome')
```

I'll put an errore when the location fallback starts so it will be easier to catch those errors.
