### ISSUE TITLE
Hourly Limit

### ISSUE THREAD

**Issue by Pretorian29** [g-battaglia/kerykeion#45]
Hi, is there any way to remove the hourly limit mentioned in the following error message:

"ERROR:root:Geonames API response could not be parsed! Maybe you exceeded API hourly limit?
ERROR:root:String that failed to parse: 

    <status message="the hourly limit of 1000 credits for century.boy has been exceeded. Please throttle your requests or use the commercial service." value="19"/>

I am trying to preprocess 85000 records to prepare a data set for an AI, can anyone gieve ideas? Thanks!

**Comment by g-battaglia** [comment]
Hi, you should create your own profile on [GeoNames](https://www.geonames.org/) and use that one instead of the default one!

**Comment by Pretorian29** [comment]
> Or also you can just insert all the data of the location and avoid using GeoNames at all

Tried using "rec = KrInstance(ID, year, month, day, hour, minute, city, country)" but only admits up to city; adding the optional country gives "root - ERROR - No results found using Geonames API!"
Thank you very much.

**Comment by Pretorian29** [comment]
Found the error: GeoNames only accept the country code as valid, not the full name of the countries. I am using AstroDataBank and despite the XML has the country code, GeoNames require me to buy credits for the purpose I am seeking in my investigation. Unfortunatley, I should use an alternative method. 
Thank you for your help.

**Comment by g-battaglia** [comment]
If you instance the KR object like this you can avoid using GeoNames:
```python
    kanye = KrInstance(
        "Kanye", 1977, 6, 8, 8, 45,
        lng=50, lat=50, tz_str="Europe/Rome"
    )
```

**Comment by Pretorian29** [comment]
> If you instance the KR object like this you can avoid using GeoNames:
> 
> ```python
>     kanye = KrInstance(
>         "Kanye", 1977, 6, 8, 8, 45,
>         lng=50, lat=50, tz_str="Europe/Rome"
>     )
> ```

Absolutely great! thank you! This Solve my problem.

**Comment by g-battaglia** [comment]
You're welcome, I'll try to update the docs to make this option more clear!

**Comment by Pretorian29** [comment]
Thank you very much for updating Giacomo. 
I am using the last version of kerykeion and works absolutely fine; Generates the data to feed an algorithm and generates the chart for a report in Angular. 
I just wanted to ask if you will be giving options to change chart colours and if it will support different languages in the future.
Once again, thank you!
