### ISSUE TITLE
Rahu, Ketu, Lilith and Chiron

### ISSUE THREAD

**Issue by sturakhanov** [g-battaglia/kerykeion#46]
Hi! Love your project, would like to contribute implementation of these objects to your project. What would be a fastest way to do so? Thanks!

**Comment by g-battaglia** [comment]
Hi, I'll implement those in the V4! Stay tuned!

**Comment by vokforever** [comment]
> Hi, I'll implement those in the V4! Stay tuned!

when will version 4 be ready approximately?

**Comment by g-battaglia** [comment]
Closing, the missing ones are not in plan so far.

**Comment by fkostadinov** [comment]
@vokforever I have implemented the south nodes (rahu and ketu) and created a pull request which is currently pending, see here: https://github.com/g-battaglia/kerykeion/pull/134
