### ISSUE TITLE
Birth Location in charts created with lat/lon set to default

### ISSUE THREAD

**Issue by Pretorian29** [g-battaglia/kerykeion#48]
I am creating charts using lat/lon like this:
kanye = KrInstance( "Kanye", 1977, 6, 8, 8, 45, lng=50, lat=50, tz_str="Europe/Rome" )

The chart shows the coordinates correctly, except the birth location, this is set to the default 'London' in every single output.
is there any way to add the location without  connecting to GeoNames?

**Comment by g-battaglia** [comment]
Hi, check [#42](https://github.com/g-battaglia/kerykeion/issues/41)

**Comment by Pretorian29** [comment]
Thank you for your reply. I am passing a string variable to tz-str that change according to the input, and still getting ther same result. 
![Screenshot 2022-09-14 132553](https://user-images.githubusercontent.com/72453357/190153555-2009e941-43af-44fe-85c9-62c303bfadf7.png)
![Screenshot 2022-09-14 132705](https://user-images.githubusercontent.com/72453357/190153561-035fca34-d0a4-443c-82b8-147c5e59eb1c.png)
Can you please give a comment about this? Thank you.

**Comment by g-battaglia** [comment]
Hi, the name of the city defaults on `"London"` if you do not give a parameter `city=%%`, in your case you should create the object giving also the parameter
`city="Tokio"`. This parameter, when you give the coordinates and the timezone, is just a name and does not change the result of the calculation.

**Comment by g-battaglia** [comment]
Hi @Pretorian29, did it work? Can I close the issue?

**Comment by Pretorian29** [comment]
Hello, sorry I could not reply over the weekend. I will try that now and I will let you know the results. thank you for your time.

**Comment by Pretorian29** [comment]
It worked! Thank you.
