### ISSUE TITLE
Another option ?

### ISSUE THREAD

**Issue by joulethieff** [g-battaglia/kerykeion#49]
I would like to have the following options.

sidereal zodiac, tropical zodiac option
house system (koch regiomontanus) option

**Comment by g-battaglia** [comment]
Hi, sidereal and tropical options are already available, you just need to add the kwarg `zodiac_type`, eg:
```test = KrInstance("Kanye", 1977, 6, 8, 8, 45, "Milano", zodiac_type="Sidereal")```
I'm currently working on the versione 4 of kr, which will include also new options of house systems and new celestial objects (Chiron and others).

**Comment by joulethieff** [comment]
I'll keep studying.
Thank you very much.


-----Original Message-----

**Comment by g-battaglia** [comment]
You're welcome, I have in plan to write down a detailed documentation for kerykeion, but the time is always less than what I would like to have. In the next month I surly will do it thought!

**Comment by pije76** [comment]
First, thank you for this awesome library and I am sorry to open this issue.
Second, can we add new celestial object by custom? Example: add new longitude/latitude by user to that new object?
It would be great feature if you can do this.
