### ISSUE TITLE
Improvment: the ability to get only transits aspects to natal chart or vice versa

### ISSUE THREAD

**Issue by javonnii** [g-battaglia/kerykeion#59]
from kerykeion import KrInstance, MakeSvgInstance

def create_svg_chart(name1, year1, month1, day1, hour1, minute1, city1, country1, zodica_type1,
                    name2, year2, month2, day2, hour2, minute2, city2, country2, zodica_type2):
    
    first = KrInstance(name1, year1, month1, day1, hour1, minute1, city1, country1, zodica_type1)
    second = KrInstance(name2, year2, month2, day2, hour2, minute2, city2, country2, zodica_type2)

    name = CompositeAspects(first, second)
    # get the aspects from transits to natal
    aspect_list = name.get_relevant_aspects() # This still gives me too many aspects, I only want the aspect from transits to natal. 
    
    
    df = pd.DataFrame(aspect_list)
    return df

**Comment by g-battaglia** [comment]
Closing, not in plan so far
