### ISSUE TITLE
Planet names are not appearing for some planets in sn.aspects

### ISSUE THREAD

**Issue by rxng** [g-battaglia/kerykeion#6]
Some of the planet names are turning up as numbers, rather than the names of the planets. e.g see below for example 1 Moon - is this meant to be Sun Moon?

Saturn Mars 1.0 Sesquiquadrate
Saturn 1 2.0 Square
Saturn 10 -6.4 Oposition
1 Moon -0.3 Sesquiquadrate
1 Venus -1.8 Trigon
1 Jupiter -1.5 Semisextil
1 10 2.0 Semisquare
10 Saturn 7.6 Conjuction
10 1 5.7 Trigon

**Comment by g-battaglia** [comment]
The numbers represent the houses, so 1 is the Ascendent, 2 is the second house and so on.

**Comment by rxng** [comment]
It only pops up 1 and 10, but no other numbers.

I assume 10 means Saturn? However it also show Saturn too, so that’s confusing

**Comment by g-battaglia** [comment]
10 is the 10th house, in the settings by default it just checks the first and the tenth house. You can change that in the file kr_settings.py in the section # Planets settings, set the visibility of the house you want to 1 and it will work.
