### ISSUE TITLE
Declinations

### ISSUE THREAD

**Issue by LiGoldragon** [g-battaglia/kerykeion#60]
Hey, this project doesn't seem to support declinations. Am I right? Parallels and contra-parallels are the strongest aspects. I'm happy to help or answer any questions.

PS: Have you seen [Dubay's 200 proofs](https://www.youtube.com/watch?v=qEaHjPF47_E)? I highly encourage you to watch it with an open mind!

Cheers!

**Comment by g-battaglia** [comment]
Hi, so far no, it's not supporting declinations, maybe in the future!
