### ISSUE TITLE
Bad location in report (London instead of Paris)

### ISSUE THREAD

**Issue by to175** [g-battaglia/kerykeion#62]
Hi, there is a bug whene generating report without GeoName.

I'm using Python 3.9.13 on Windows with Jupyter Notebook

```
kanye = KrInstance(
    "Name", 1990, 5, 5, 15, 50,
    lng=2.3488, lat=48.8534, tz_str="Europe/Paris"
    )
report = Report(kanye)
report.print_report()
print(repr(report.__dict__))
```

- Kerykeion report for Name -+
+----------+-------+----------+-----------+----------+
| Date     | Time  | Location | Longitude | Latitude |
+----------+-------+----------+-----------+----------+
| 5/5/1990 | 15:50 | **London,**  | 2.3488    | 48.8534  |
+----------+-------+----------+-----------+----------+
...
Birth location: **London,** Lat 48.8534, Lon 2.3488
...

The script is not about to find the city is **Paris, FR** and not London...

**Comment by g-battaglia** [comment]
Hi, if you do not specify the name of the city it defaults to London. Just for the name though, the coordinates are the ones that you inserted

**Comment by to175** [comment]
I have filled the informations exactlly as asked in doc
```
kanye = KrInstance(
    "Name", 1990, 5, 5, 15, 50,
    lng=2.3488, lat=48.8534, tz_str="Europe/**Paris**"
    )
```

Where to "specify the name of the city" please ?

**Comment by g-battaglia** [comment]
https://github.com/g-battaglia/kerykeion#usage

**Comment by g-battaglia** [comment]
```
# Create a kerykeion instance:
# Args: Name, year, month, day, hour, minuts, city, nation(optional)
kanye = KrInstance("Kanye", 1977, 6, 8, 8, 45, "Atlanta")
```

**Comment by g-battaglia** [comment]
The usage section is pretty clear, there is an argument called city. You can also specified it as a kwarg:
`kanye = KrInstance("Kanye", 1977, 6, 8, 8, 45, city="Atlanta")`

**Comment by g-battaglia** [comment]
I'll switch the default location name to default, so it will be clear that it's default and not just London (GMT).
Thank you for your feedback.

**Comment by to175** [comment]
I'm am not creating a classic instance with GeoNames. I am trying to use kerykeion without geonames. So I understand there, if you use kerykeion like that, it will take the good latitude and longitude to make the right calculs, however, it will not display the right city on the report and this is normal. Even if I mentioned /Paris in addition of the coordinates...
