### ISSUE TITLE
Numeric degrees values display in the Natal chart's degreeRing

### ISSUE THREAD

**Issue by drzraf** [g-battaglia/kerykeion#64]
There should be a setting to display the common numeric (approx) values of planets and houses all around the outside degree ring.

**Comment by g-battaglia** [comment]
Hi, that feature is not in plan so far.

**Comment by drzraf** [comment]
Fine (but I maintain that this [numeric value] display would make sense, even if, I agree, it's a bit painful to generate using SVG semantics)
