### ISSUE TITLE
Permission error "write a readonly database"

### ISSUE THREAD

**Issue by to175** [g-battaglia/kerykeion#70]
Hello,

I can run my app with kerykeion on local however I have these errors when i put it on my server... All perms are good (777) and the city also. I don't understand why I got these errors which are not correlated to my bug. What is the first error ? "attempt to write a readonly database" ? is it from http://api.geonames.org/searchJSON ? Errors are not clear at all

PermissionError(13, 'Permission denied')

Full traceback :

```
2023-06-14 11:55:17,591 - KrInstance - ERROR - Error in fetching http://api.geonames.org/searchJSON: attempt to write a readonly database
2023-06-14 11:55:17,591 - KrInstance - ERROR - Error in fetching timezone: 'lat'
raise KerykeionException(
kerykeion.types.KerykeionException: No data found for this city, try again! Maybe check your connection?
```

**Comment by g-battaglia** [comment]
It looks like your fetching timezone for `lat`, I belive it's not a issue with the library.

**Comment by to175** [comment]
I understand. However the code works fine in local env and I use very simple config like this  `KrInstance('name, 1990, 1, 1, 10, 30, 'Paris')`

I dont understand why kerykeion throw me 
`2023-06-14 13:40:16,532 - KrInstance - ERROR - Error in fetching http://api.geonames.org/searchJSON: attempt to write a readonly database`

Which error comes from
```
self.responses[cache_key] = cached_response
  File "/home/debian/Desktop/bot/botscript/venv/lib/python3.9/site-packages/requests_cache/backends/sqlite.py", line 283, in __setitem__
    con.execute(
sqlite3.OperationalError: attempt to write a readonly database
```

**Comment by to175** [comment]
Maybe the issue is my db is locked but this is not an appropriate error for this kind of basic issue, I don't even know where is the database, all this seems difficult to troubleshoot with these errors :/

Where is kerykeion DB located please?
