### ISSUE TITLE
not importing with anaconda3

### ISSUE THREAD

**Issue by kgola** [g-battaglia/kerykeion#88]
Excellent package, but I switched my device and installed Jupyter via homebrew and can't find the kerykeion modules when I import them to Jupyter. Getting the error `module 'kerykeion' has no attribute 'X' after trying to run the any module. Jupyter is in `/anaconda3/bin/jupyter` and the package is in `/anaconda3/lib/python3.11/site-packages` so those should connect, no?

**Comment by g-battaglia** [comment]
Can you report the whole code fragment?

**Comment by g-battaglia** [comment]
Closing because of no further updates
