### ISSUE TITLE
Problem with open Natal chart type svg

### ISSUE THREAD

**Issue by DaydreamerSY** [g-battaglia/kerykeion#9]
Here is my code:
```
import kerykeion as kr
from kerykeion.utilities.charts import MakeSvgInstance

first = kr.KrInstance("Jack", 1990, 6, 15, 15, 15, "Roma")

name = MakeSvgInstance(first)
# name = MakeSvgInstance(first, chart_type="Natal")
name.output_directory = "./charts/"
name.makeSVG()
```
It worked very well, but when I try to open it in browsers or make png, I got errors.
This is in browsers:
```
This page contains the following errors:
error on line 18 at column 60: Encoding error
Below is a rendering of the page up to the first error.
Jack
Info:
Roma
1999-9-30 10:30
```
And this occurred when I try to create PNG using `svglib` lib:
`AttributeError: 'NoneType' object has no attribute 'renderScale'`

**Comment by DaydreamerSY** [comment]
I found that some thing went wrong with `Latitude` and `Longitude` when generate svg file, I try to delete both geo-row in svg, it worked.

**Comment by DaydreamerSY** [comment]
I'm sorry if I messed it up, It totally because my pc, nothing wrong with repos. You can close this issue as well, have nice days.

**Comment by DaydreamerSY** [comment]
Finally, I fixed it, just replace degree sign `°` with `&#176;` in `lat2str` and `lon2str` method in `charts_svg.py`, It worked more smoothly, hopes you can update it soon.

Best regard,
Loc

**Comment by g-battaglia** [comment]
Thank you, you can make a pull request if you want, it would be helpful! Otherwise I'll update it and test it as soon as I can.
